import type { Metadata } from 'next'
import { Inter } from '@next/font/google'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import 'bootstrap/dist/css/bootstrap.css'
import './styles/globals.css'
import BootstrapClient from '../../components/BootstrapClient'


const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'KongShop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar/>
          {children}
          <Footer/>
          <BootstrapClient/>
      </body>
    </html>
  )
}
